"""crear tabla users

Revision ID: 67e278a87760
Revises: 
Create Date: 2025-09-08 19:16:50.229988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e278a87760'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('membership', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('tall', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('fitness_level', sa.String(length=255), nullable=True),
    sa.Column('fitness_objective', sa.String(length=255), nullable=True),
    sa.Column('medical_condition', sa.String(length=255), nullable=True),
    sa.Column('allergies', sa.String(length=255), nullable=True),
    sa.Column('class_reminder', sa.Boolean(), nullable=True),
    sa.Column('payment_reminder', sa.Boolean(), nullable=True),
    sa.Column('class_summary', sa.Boolean(), nullable=True),
    sa.Column('promotions_offers', sa.Boolean(), nullable=True),
    sa.Column('social_updates', sa.Boolean(), nullable=True),
    sa.Column('visible_profile', sa.Boolean(), nullable=True),
    sa.Column('share_progress', sa.Boolean(), nullable=True),
    sa.Column('show_ranking', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
