"""create table clases

Revision ID: d6f307ccf761
Revises: 744c95f86d6c
Create Date: 2025-09-16 16:44:49.125213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f307ccf761'
down_revision: Union[str, Sequence[str], None] = '744c95f86d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('zona', sa.String(length=100), nullable=False),
    sa.Column('hora', sa.DateTime(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('profesor', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clases')
    # ### end Alembic commands ###
